# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Danilo Val
email: danilodoval@gmail.com
keyword: "Blog, tecnologia, TI, iOS, Apple, iPhone"
description: >- # this means to ignore newlines until "baseurl:"
  Desenvolvimento de software, tecnologia e afins.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daniloval.com"
twitter_username: dnlval
github_username:  daniloval

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-compose
  - jekyll-algolia
  - jekyll-youtube
  - jekyll-analytics

utterance:
  repo: daniloval//daniloval.github.io
  issue-term: title
  theme: github-light

  label: blog-comments # Choose the label that will be assigned to issues created by Utterances.


jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-ETDZVH7XPP        # Required - replace with your tracking id
    anonymizeIp: true       # Optional - Default: false - set to true for anonymized tracking

  # Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
  #   url: matomo.example.com # Required - url to Matomo installation without trailing /
  #   siteId: "1234"          # Required - replace with your Matomo site id (Write id as string)

  # Piwik:                    # Add, if you want to track with Piwik
  #   url: piwik.example.com  # Required - url to Piwik installation without trailing /
  #   siteId: "1234"          # Required - replace with your Piwik site id (Write id as string)

  # MPulse:                   # Add if you want to track performance with mPulse
  #   apikey: XXXXX-YYYYY-ZZZZZ-AAAAA-23456   # Required - replace with your mPulse API key

  # Plausible:
  #   domain: 'example.com'   # The domain configured in plausible
  #   source: 'https://plausible.example.com/js/plausible.js' # The source of the javascript

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
